### ISSUE TITLE
Error saving content

### ISSUE THREAD

**Issue by ghost** [leekelleher/umbraco-nested-content#137]
I'm getting an error trying to save my first content element with a Nested Content widget.

When I do not populate my Nested Content widget on the page, I'm able to [save & publish] this content element.  When I populate my Nested Content widget I get this stack trace...

```
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

Any suggestions on troubleshooting my Nested Content widget?

**Comment by leekelleher** [comment]
Hi @s15199d - thanks for raising this.

The stack-trace exception message doesn't reference Nested Content, so I'm not sure where the issue might be coming from.  Although there are a few mentions of `AuthorizationFilterAttribute` in there... could be a permissions issue? (again, not sure how that's related to Nested Content at this point).

**Comment by ghost** [comment]
@leekelleher thanks for your response.  I hear what you're saying.  I narrowed the error down to a specific property of my NC widget.  Umbraco throws the error when I upload an image (using the image cropper editor) to my NC widget.  If I don't upload an image to my NC widget it saves without error.  Any idea why uploading an image using the image cropper editor to my NC widget would cause it to fail?

**Comment by leekelleher** [comment]
@s15199d - Ah ok, the Image Cropper (nor Upload) controls will not work with Nested Content, it's a [known issue](https://github.com/umco/umbraco-nested-content#known-issues) (there are some other controls that don't work either). Sorry.

Our recommendation is to have images uploaded to the media section and use the media-picker control.
